/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_speex_speexprocess */

#ifndef _Included_com_speex_speexprocess
#define _Included_com_speex_speexprocess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_speex_speexprocess
 * Method:    Speex_init
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_speex_speexprocess_Speex_1init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_speex_speexprocess
 * Method:    Speex_exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_speex_speexprocess_Speex_1exit
  (JNIEnv *, jobject);

/*
 * Class:     com_speex_speexprocess
 * Method:    Speex_process
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_speex_speexprocess_Speex_1process
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray,jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
